### ISSUE TITLE
Links look like broken

### ISSUE THREAD

**Issue by yahu1031** [nyxx-discord/running_on_dart#19]
I used `/docs search` command and it gave me the results but the links for them look broken.

**Comment by l7ssha** [comment]
Will take a look :)

**Comment by l7ssha** [comment]
I just take a look at docs stuff and it seems like its completely broken and needs complete rewrite. It will be my priority to fix these poblems

**Comment by l7ssha** [comment]
Fixed: https://canary.discord.com/channels/846136758470443069/846137180345729064/927350827042095215
